/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs41acl.h"

bool_t
xdr_zacetype4 (XDR *xdrs, zacetype4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_zaceflag4 (XDR *xdrs, zaceflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_zaceiflag4 (XDR *xdrs, zaceiflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_zacemask4 (XDR *xdrs, zacemask4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfsace4i (XDR *xdrs, nfsace4i *objp)
{
	register int32_t *buf;

	 if (!xdr_zacetype4 (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_zaceflag4 (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_zaceiflag4 (xdrs, &objp->iflag))
		 return FALSE;
	 if (!xdr_zacemask4 (xdrs, &objp->access_mask))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->who))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_zaclflag4 (XDR *xdrs, zaclflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfsacl41i (XDR *xdrs, nfsacl41i *objp)
{
	register int32_t *buf;

	 if (!xdr_zaclflag4 (xdrs, &objp->na41_flag))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->na41_aces.na41_aces_val, (u_int *) &objp->na41_aces.na41_aces_len, ~0,
		sizeof (nfsace4i), (xdrproc_t) xdr_nfsace4i))
		 return FALSE;
	return TRUE;
}
